import React, { useState, useEffect } from "react";
import Head from 'next/head'
import { Container, Form, Button, Row, Col } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import GroundStationModal from '../components/GroundStationModal'
import styles from '../styles/dashboard.module.scss'
import axios from "axios";

export default function AddGS() {
  const [hideShowSidebar, setHideShowSidebar] = useState(true);
  const [modalShow, setModalShow] = useState(false);
  const [stationName, setStationName] = useState("Name");
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <DashBoardHeader 
          setHideShowSidebar = {setHideShowSidebar}
          hideShowSidebar = {hideShowSidebar}
        />
        <Sidebar 
          hideShowSidebar={hideShowSidebar}
        />
        <div className={hideShowSidebar ? "dashboardContent" : "dashboardContent sidebar--open"}>
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <Form className={styles.customForm}>
                <h4>Add Ground Stations</h4>
                <Row className={styles.formRow}>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Form.Label>Name</Form.Label>
                    <Form.Control type="text" />
                  </Form.Group>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Form.Label>Elevation</Form.Label>
                    <Form.Control type="text" />
                  </Form.Group>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Form.Label>Latitude</Form.Label>
                    <Form.Control type="text" />
                  </Form.Group>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Form.Label>Longitude</Form.Label>
                    <Form.Control type="text" />
                  </Form.Group>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Form.Label>Uplink Rate</Form.Label>
                    <Form.Control type="text"/>
                  </Form.Group>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Form.Label>Downlink Rate</Form.Label>
                    <Form.Control type="text"/>
                  </Form.Group>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Form.Label>Mask</Form.Label>
                    <Form.Control type="text"/>
                  </Form.Group>
                  <Form.Group as={Col} md={6} className={styles.formGroup}>
                    <Button type="button" className={styles.submitBtn} onClick={() => setModalShow(true)}>Submit</Button>
                  </Form.Group>
                </Row>
              </Form>
            </Container>
          </div>
        </div>
      </main>
      <GroundStationModal 
        show={modalShow}
        onHide={() => setModalShow(false)}
        stationName={stationName}
      />
    </>
  )
}
