"use client";

import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Container, Button } from "react-bootstrap";
import Sidebar from "../components/Sidebar";
import DashBoardHeader from "../components/DashBoardHeader";
import DataTable from "../components/DataTable";
import styles from "../styles/dashboard.module.scss";
import AddGSModal from "../components/AddGSModal";
import AddSATModal from "../components/AddSATModal";
import { MdAdd } from "react-icons/md";
import axios from "axios";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import Box from "@mui/material/Box";
import Viewer2D from "@/components/Map/Viewer2D/Viewer2D";
import Viewer3D from "@/components/Map/Viewer3D/Viewer3D";
import useWebSocket, { ReadyState } from "react-use-websocket";

const WS_URL = "ws://localhost:5000/assets/satellites/1/state";

const columns = [
  {
    Header: "GS",
    accessor: "gs",
  },
  {
    Header: "In Contact",
    accessor: "inContact",
  },
  {
    Header: "Duration",
    accessor: "duration",
  },
  {
    Header: "Lost of signal",
    accessor: "lostOfSignal",
  },
];

// when you add API Url just comment this
const data = [
  {
    gs: 1,
    inContact: "SAT 1",
    duration: "10 minutes",
    lostOfSignal: "16:30:00",
  },
  {
    gs: 1,
    inContact: "False",
    duration: "False/O",
    lostOfSignal: "00:00:00",
  },
  {
    gs: 1,
    inContact: "SAT 4",
    duration: "12 minutes",
    lostOfSignal: "18:40:00",
  },
];

const columns2 = [
  {
    Header: "SAT",
    accessor: "sat", // Property name in your data
  },
  {
    Header: "Storage Current",
    accessor: "storageCurrent",
  },
  {
    Header: "Main",
    accessor: "main",
  },
  {
    Header: "Out",
    accessor: "out",
  },
  {
    Header: "Power",
    accessor: "power",
  },
];

// when you add API Url just comment this
const data2 = [
  {
    sat: 1,
    storageCurrent: "32gb",
    main: "False",
    out: "False",
    power: "Eclipse",
  },
  {
    sat: 2,
    storageCurrent: "16gb",
    main: "True",
    out: "False",
    power: "Sunlight",
  },
];

export default function AssetStatus() {
  const { sendMessage, lastMessage, readyState } = useWebSocket(WS_URL);

  const [satellite, setSatellite] = useState(null);

  const connectionStatus = {
    [ReadyState.CONNECTING]: "Connecting",
    [ReadyState.OPEN]: "Open",
    [ReadyState.CLOSING]: "Closing",
    [ReadyState.CLOSED]: "Closed",
    [ReadyState.UNINSTANTIATED]: "Uninstantiated",
  }[readyState];

  // uncomment the below line when you add link in axios
  // const [data, setData] = useState([]);
  const [currentTime, setCurrentTime] = useState(new Date());
  const [openDropdown, setOpenDropdown] = useState(false);

  const [showModal1, setShowModal1] = useState(false);
  const [showModal2, setShowModal2] = useState(false);
  const [value, setValue] = React.useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
    if (newValue == 0) {
    }
  };

  useEffect(() => {
    console.log("Current connection status: " + connectionStatus);
    console.log(
      "Data: " + (lastMessage == null ? "no data" : lastMessage.data)
    );
  }, [readyState, lastMessage]);

  useEffect(() => {
    setSatellite(lastMessage == null ? null : lastMessage.data);
  }, [lastMessage]);

  useEffect(() => {
    // just change the url and uncomment the inner code
    axios.get("https://jsonplaceholder.typicode.com/users").then((response) => {
      // setData(response.data);
    });

    const intervalId = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000); // Update every second

    return () => {
      clearInterval(intervalId);
    };
  }, []);

  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dashboard">
        <Sidebar />
        <DashBoardHeader />
        <div className="dashboardContent">
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <Box sx={{ width: "100%", marginBottom: "15px" }}>
                <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
                  <Tabs value={value} onChange={handleChange} aria-label="Tabs">
                    <Tab label="ASSET STATUS" />
                    <Tab label="ASSET MAPS" />
                  </Tabs>
                </Box>
              </Box>
              {value == 0 ? (
                <div className={styles.dashboardContentRow}>
                  <div className={styles.TableCol}>
                    <div className={styles.TableHeading}>
                      <h4>{currentTime.toLocaleString()}</h4>
                      <h1>Hello {connectionStatus}</h1>
                      <p>Satellite 1: {satellite}</p>
                      <div className={styles.assetsDropdown}>
                        <Button
                          type="button"
                          className={styles.assetsDropdownBtn}
                          onClick={() => setOpenDropdown(!openDropdown)}
                        >
                          <MdAdd />
                          Add Assets
                          {/* {dropdown1 ? <IoIosArrowUp /> : <IoIosArrowDown />} */}
                        </Button>
                        {openDropdown && (
                          <div className={styles.assetsDropdownMenu}>
                            <Button
                              type="button"
                              onClick={() => setShowModal1(true)}
                            >
                              <span>Add Station</span>
                            </Button>
                            <Button
                              type="button"
                              onClick={() => setShowModal2(true)}
                            >
                              <span>Add Satellite</span>
                            </Button>
                          </div>
                        )}
                      </div>
                    </div>
                    <DataTable
                      search={false}
                      tablePagination={true}
                      columns={columns}
                      data={data}
                      rowSeletion={false}
                      actionBtn={false}
                      actionBtnText=""
                    />
                    <hr />
                    <DataTable
                      search={false}
                      tablePagination={true}
                      columns={columns2}
                      data={data2}
                      rowSeletion={false}
                      actionBtn={false}
                      actionBtnText=""
                    />
                  </div>
                </div>
              ) : (
                <>
                  <Viewer2D></Viewer2D>
                  <Viewer3D></Viewer3D>
                </>
              )}
            </Container>
          </div>
        </div>
      </main>
      <AddGSModal showModal1={showModal1} setShowModal1={setShowModal1} />
      <AddSATModal showModal2={showModal2} setShowModal2={setShowModal2} />
    </>
  );
}
