import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Container, Button, Row, Col, Stack, ListGroup } from "react-bootstrap";
import Sidebar from "../components/Sidebar";
import DashBoardHeader from "../components/DashBoardHeader";
import styles from "../styles/dashboard.module.scss";
import { CircularProgressbar } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";
import DataTable from "@/components/DataTable";
import { BarChart } from "@mui/x-charts/BarChart";
import { PieChart } from "@mui/x-charts/PieChart";

export default function Home() {
  // uncomment the below line when you add link in axios
  // const [data, setData] = useState([]);

  const percentage = 30;

  const orderStatuses = () => {
    let returnable = {};
    for (let i = 0; i < 10; i++) {
      returnable["Order" + i] =
        Math.floor(Math.random() * 2) + 1 == 1 ? "Complete" : "Incomplete";
    }
    return returnable;
  };

  const ordersFulfilledColumnHeaders = [
    { Header: "Order #", accessor: "order" },
    { Header: "Status", accessor: "status" },
  ];
  const ordersFulfilledMockData = [
    { order: "Order 1", status: "true" },
    { order: "Order 2", status: "false" },
    { order: "Order 3", status: "true" },
    { order: "Order 4", status: "true" },
  ];

  const mockUtilizationData = [
    { satellite: "SAT1", usage: 30 },
    { satellite: "SAT2", usage: 15 },
    { satellite: "SAT3", usage: 37 },
    { satellite: "SAT4", usage: 5 },
    { satellite: "SAT4", usage: 80 },
  ];

  const pieChartData = [
    { id: 0, value: 3, label: "SAT1" },
    { id: 1, value: 15, label: "SAT2" },
    { id: 2, value: 20, label: "SAT3" },
    { id: 3, value: 20, label: "SAT4" },
    { id: 4, value: 40, label: "SAT5" },
  ];
  const data = {
    labels: mockUtilizationData.map((data) => {
      return data.satellite;
    }),
    datasets: [
      {
        label: "My First dataset",
        backgroundColor: "rgb(255, 99, 132)",
        borderColor: "rgb(255, 99, 132)",
        data: mockUtilizationData.map((data) => {
          return data.usage;
        }),
      },
    ],
  };

  const [ordersFulfilled, setOrdersFulfilled] = useState(null);

  useEffect(() => {
    setOrdersFulfilled(orderStatuses());
  }, []);

  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dashboard">
        <Sidebar />
        <DashBoardHeader />
        <div className="dashboardContent">
          <Container>
            <br />
            <Stack className="align-items-center">
              <div style={{ width: "25%", height: "25%", textSize: "15px" }}>
                <CircularProgressbar
                  value={percentage}
                  text={`${percentage}%`}
                />
              </div>
            </Stack>
            <div>
              <br />
              <h5 className="text-center">
                Satellite Orders and their statuses
              </h5>
              <DataTable
                search={false}
                tablePagination={true}
                actionBtn={true}
                rowSeletion={false}
                columns={ordersFulfilledColumnHeaders}
                data={ordersFulfilledMockData}
              />
            </div>
            <br />
            <hr />
            <br />
            <Row>
              <Col>
                <Stack className="align-items-center">
                  <h6>Asset Power Bar Chart</h6>
                  <div>
                    <BarChart
                      dataset={mockUtilizationData}
                      yAxis={[{ scaleType: "band", dataKey: "satellite" }]}
                      series={[
                        {
                          dataKey: "usage",
                          label: "Usage",
                        },
                      ]}
                      layout="horizontal"
                      {...{
                        xAxis: [
                          {
                            label: "Power Usage",
                          },
                        ],
                        width: "500",
                        height: "500",
                      }}
                    />
                  </div>
                </Stack>
              </Col>

              <Col>
                <Stack>
                  <h6>Asset Order Amounts Bar Chart</h6>
                  <div>
                    <PieChart
                      series={[
                        {
                          data: pieChartData,
                          highlightScope: {
                            faded: "global",
                            highlighted: "item",
                          },
                          faded: {
                            innerRadius: 30,
                            additionalRadius: -30,
                            color: "gray",
                          },
                        },
                      ]}
                      height={300}
                      width={300}
                    />
                  </div>
                </Stack>
              </Col>

              <Col>
                <Stack className="align-items-center">
                  <h6>Asset Storage Bar Chart</h6>
                  <div>
                    <BarChart
                      dataset={mockUtilizationData}
                      yAxis={[{ scaleType: "band", dataKey: "satellite" }]}
                      series={[
                        {
                          dataKey: "usage",
                          label: "Usage",
                        },
                      ]}
                      layout="horizontal"
                      {...{
                        xAxis: [
                          {
                            label: "Storage",
                          },
                        ],
                        width: "500",
                        height: "500",
                      }}
                    />
                  </div>
                </Stack>
              </Col>
            </Row>
            <br />
            <hr />
            <br />
            <Stack className="align-items-center">
              <h4>System Alerts</h4>
            </Stack>
          </Container>
        </div>
      </main>
    </>
  );
}
