import React, { useState } from 'react'
import Head from 'next/head'
import { Container, Button, Form, Row, Col } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import MaintenanceOrderModal from '../components/MaintenanceOrderModal'
import styles from '../styles/dashboard.module.scss'


export default function MaintenanceRequest() {
  const [hideShowSidebar, setHideShowSidebar] = useState(true);
  const [modalShow, setModalShow] = useState(false);
  return (
    <>
      <Head>
        <title>SOSO Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <DashBoardHeader
          setHideShowSidebar={setHideShowSidebar}
          hideShowSidebar={hideShowSidebar}
        />
        <Sidebar
          hideShowSidebar={hideShowSidebar}
        />
        <div className={hideShowSidebar ? "dashboardContent" : "dashboardContent sidebar--open"}>
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <div className={styles.dashboardContentRow}>
                <Form className={styles.customForm}>
                  <Row className={styles.formRow}>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Target</Form.Label>
                      <Form.Control type="text" placeholder="Enter Target" required/>
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Activity</Form.Label>
                      <Form.Control type="text" placeholder="Enter Activity" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Window Start</Form.Label>
                      <Form.Control type="text" placeholder="Enter Window Start" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Window End</Form.Label>
                      <Form.Control type="text" placeholder="Enter Window End" required />
                    </Form.Group>
                    <Form.Group as={Col} md="12" className={styles.formCol}>
                      <Form.Label>Duration</Form.Label>
                      <Form.Control type="text" placeholder="Enter Duration" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>RepeatCycle Frequency MinimumGap</Form.Label>
                      <Form.Control type="text" placeholder="Enter MinimumGap" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>RepeatCycle Frequency MaximumGap</Form.Label>
                      <Form.Control type="text" placeholder="Enter MaximumGap" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>RepeatCycle Repetition</Form.Label>
                      <Form.Control type="text" placeholder="Enter RepeatCycle Repetition" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>PayloadOutage</Form.Label>
                      <Form.Select>
                        <option>Select PayloadOutage</option>
                        <option value="0">False</option>
                        <option value="1">True</option>
                      </Form.Select>
                    </Form.Group>
                  </Row>
                  <Button type="button"  onClick={() => setModalShow(true)}>Submit Data</Button>
                </Form>
              </div>
            </Container>
          </div>
        </div>
      </main>
      <MaintenanceOrderModal
        show={modalShow}
        onHide={() => setModalShow(false)}
      />
    </>
  )
}
