import React, { useState, useEffect } from "react";
import Head from 'next/head'
import { Container, Button, Modal } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import { MdAdd } from "react-icons/md";
import styles from '../styles/dashboard.module.scss'
import axios from "axios";
import OrderView from "@/components/order_tables/OrderView";
import RequestsView from "@/components/order_tables/RequestsView";
import MaintenanceOrderCreationModal from "../components/order_creation_modals/MaintenanceOrderCreationModal";
import { Box, Tab, Tabs, Select, InputLabel, MenuItem, FormControl } from "@mui/material";


export default function MaintenanceOrders() {
  const [requestViewOrderIds, setRequestViewOrderIds] = useState([])
  const [initialSelectedOrderIds, setInitialSelectedOrderIds] = useState([])
  const [showModal, setShowModal] = useState(false);
  const [tab, setTab] = useState(0);

  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <Sidebar/>
        <DashBoardHeader />
        <div className="dashboardContent">
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <Button type="button" className={styles.maintenanceOrderCreateBtn} onClick={() => setShowModal(true)}><MdAdd /> CREATE OUTAGE ORDER</Button>
              <Box sx={{ width: "100%", marginBottom: "15px" }}>
                <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
                  <Tabs value={tab} onChange={(_, value) => setTab(value)} aria-label="Tabs">
                    <Tab label="Outage Orders" />
                    <Tab label="Schedule Requests" />
                  </Tabs>
                </Box>
              </Box>
              <Box sx={{ width: "100%", marginBottom: "15px" }}>
                {tab === 0 && <OrderView orderType="outage" initialSelectedOrderIds={initialSelectedOrderIds}/>} 
                {tab === 1 && <RequestsView orderType="outage" orderIds={requestViewOrderIds} onOrderFilterUpdated={(orderIds) => setRequestViewOrderIds(orderIds) && setInitialSelectedOrderIds(orderIds)}/>}
              </Box>
            </Container>
          </div>
        </div>
      </main>
      <MaintenanceOrderCreationModal
        showModal={showModal} 
        setShowModal={setShowModal}
      />
    </>
  )
}





import React, { useState, useEffect } from "react";
import Head from 'next/head'
import { Container, Button, Modal } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import DataTable from '../components/order_tables/DataTable'
import OutageRequestsModal from '../components/OutageRequestsModal'
import { MdAdd } from "react-icons/md";
import styles from '../styles/dashboard.module.scss'
import axios from "axios";

const columns = [
  {
    Header: 'Target',
    accessor: 'target', 
  },
  {
    Header: 'Start Time',
    accessor: 'startTime',
  },
  {
    Header: 'End Time',
    accessor: 'endTime',
  },
  // Add more columns as needed
];

const data = [{
  target: "SOSO-1",
  startTime: "2024-01-08 T00:00:00",
  endTime: "2024-10-08 T00:00:00",
}];

export default function OutageRequests() {
  // uncomment the below line when you add link in axios
  // const [data, setData] = useState([]);
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    // just change the url and uncomment the inner code
    axios.get("https://jsonplaceholder.typicode.com/users").then((response) => {
      // setData(response.data);
    });
  }, []);
  
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <Sidebar/>
        <DashBoardHeader />
        <div className="dashboardContent">
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <Button type="button" className={styles.outageRequestsBtn} onClick={() => setShowModal(true)}><MdAdd />Add Outage</Button>
              <div className={styles.dashboardContentRow}>
                <div className={styles.TableCol}>
                  <DataTable 
                    search = {false}
                    tablePagination = {true}
                    columns = {columns}
                    data = {data}
                    outageRequestsButton = {true}
                    rowSeletion = {true}
                    actionBtn= {true}
                    actionBtnText= "Decline"
                  />
                </div>
              </div>
            </Container>
          </div>
        </div>
      </main>
      <OutageRequestsModal
        showModal={showModal} 
        setShowModal={setShowModal}
      />
    </>
  )
}
