import React, { useState } from 'react'
import Head from 'next/head'
import { Container, Button, Form, Row, Col } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import DataTable from '../components/DataTable'
import styles from '../styles/dashboard.module.scss'


export default function OutageRequest() {
  const [hideShowSidebar, setHideShowSidebar] = useState(true);
  return (
    <>
      <Head>
        <title>SOSO Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <DashBoardHeader
          setHideShowSidebar={setHideShowSidebar}
          hideShowSidebar={hideShowSidebar}
        />
        <Sidebar
          hideShowSidebar={hideShowSidebar}
        />
        <div className={hideShowSidebar ? "dashboardContent" : "dashboardContent sidebar--open"}>
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <div className={styles.dashboardContentRow}>
                <Form className={styles.customForm}>
                  <Row className={styles.formRow}>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Target</Form.Label>
                      <Form.Control type="text" placeholder="Enter Target" required/>
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Activity</Form.Label>
                      <Form.Control type="text" placeholder="Enter Activity" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Window Start</Form.Label>
                      <Form.Control type="text" placeholder="Enter Window Start" required />
                    </Form.Group>
                    <Form.Group as={Col} md="6" className={styles.formCol}>
                      <Form.Label>Window End</Form.Label>
                      <Form.Control type="text" placeholder="Enter Window End" required />
                    </Form.Group>
                  </Row>
                  <Button type="submit">Submit Data</Button>
                </Form>
              </div>
            </Container>
          </div>
        </div>
      </main>
    </>
  )
}
