import React, { useState, useEffect } from "react";
import Head from 'next/head'
import { Container, Button, Modal } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import DataTable from '../components/DataTable'
import MaintenanceRequestModal from '../components/MaintenanceRequestModal'
import styles from '../styles/dashboard.module.scss'
import axios from "axios";

const columns = [
  {
    Header: 'Dummy text',
    accessor: 'target', 
  },
  {
    Header: 'Dummy text',
    accessor: 'activity',
  },
  {
    Header: 'Dummy text',
    accessor: 'windowStart',
  },
  {
    Header: 'Dummy text',
    accessor: 'windowEnd',
  },
  {
    Header: 'Dummy text',
    accessor: 'duration',
  },
  // Add more columns as needed
];

const data = [{
  target: "Lorem apsum",
  activity: "Lorem apsum",
  windowStart: "Lorem apsum",
  windowEnd: "Lorem apsum",
  duration: "Lorem apsum",
}];

export default function Schedules() {
  // uncomment the below line when you add link in axios
  // const [data, setData] = useState([]);
  
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <Sidebar/>
        <DashBoardHeader />
        <div className="dashboardContent">
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <div className={styles.dashboardContentRow}>
                <div className={styles.TableCol}>
                  <DataTable 
                    search = {false}
                    tablePagination = {true}
                    columns = {columns}
                    data = {data}
                    rowSeletion = {true}
                    actionBtn= {true}
                    actionBtnText= "Decline"
                  />
                </div>
              </div>
            </Container>
          </div>
        </div>
      </main>
    </>
  )
}
