import React, { useState, useEffect } from "react";
import Head from 'next/head'
import { Container } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import styles from '../styles/dashboard.module.scss'
import axios from "axios";
import SystemTime from "../components/SystemTime";
import ScheduleRequests from "../components/ScheduleRequests";
import ScheduleTimeline from "../components/schedule/ScheduleTimeline"
import EventsView from "@/components/tables/EventsView";
import { MultiSelect } from "react-multi-select-component";
import { Box, Tab, Tabs, Select, InputLabel, MenuItem, FormControl } from "@mui/material";

export async function getStaticProps() {
  let base_url = process.env.NEXT_PUBLIC_BASE_API_URL
  const response = await axios.get(`${base_url}/schedules/`)
  const data = response.data.reduce((acc, schedule_json) => {
    acc[schedule_json['name']] = schedule_json
    return acc
  }, {})
  return {
    props: {
      schedules: data,
    }
  }
}

let eventTypeOptions = ["imaging", "maintenance", "gs_outage", "sat_outage", 'contact', 'eclipse', 'capture', 'transmission_outage'].map((event_type) => ({label: event_type, value: event_type}))
// default is first four options
let defaultEventTypes = eventTypeOptions.slice(0, 4)

export default function ScheduleView({schedules}) {
  const defaultScheduleName = "Default Schedule"
  const [tab, setTab] = useState(0);
  const [currentScheduleName, setCurrentScheduleName] = useState(defaultScheduleName)
  const [scheduledEvents, setScheduledEvents] = useState([])
  const [scheduleId, setScheduleId] = useState(null)
  const [selectedEventTypes, setSelectedEventTypes] = useState(defaultEventTypes)

  const updateScheduledEvents = async (currentScheduleName, scheduleInfos) => {
    try {
      let eventTypesFilter = ""
      if (selectedEventTypes.length > 0) {
        eventTypesFilter = '?event_types=' + selectedEventTypes.map((type) => type.value).join('&event_types=')
      }
      
      let base_url = process.env.NEXT_PUBLIC_BASE_API_URL
      let url = `${base_url}/schedules/${scheduleInfos[currentScheduleName]?.id}/events${eventTypesFilter}`
      const response = await axios.get(url)
      setScheduledEvents(response.data.data)
      setScheduleId(scheduleInfos[currentScheduleName]?.id)
    } catch (error) {
      setScheduledEvents([])
      throw error;
    }
  }

  useEffect(() => {
    updateScheduledEvents(currentScheduleName, schedules)
  }, [currentScheduleName, selectedEventTypes])

  const [timeConstraint, setTimeConstraint] = useState(1);

  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <Sidebar/>
        <DashBoardHeader />
        <div className="dashboardContent">
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <FormControl>
                <InputLabel id="schedule-select-label">Schedule</InputLabel>
                <Select
                  labelId="schedule-select-label"
                  id="schedule-select"
                  defaultValue={defaultScheduleName}
                  label="Schedule"
                  onChange={(event) => setCurrentScheduleName(event.target.value)}
                >
                  {Object.keys(schedules).map((schedule_name, idx) => (
                    <MenuItem key={idx} value={schedule_name.trim()}>{schedule_name}</MenuItem>
                  ))}
                </Select>
              </FormControl>
              {/* <FormControl>
                <InputLabel id="time-constraint-label">Time Constraint</InputLabel>
                <Select
                  labelId="time-constraint-label"
                  id="time-constraint-select"
                  value={timeConstraint}
                  label="Time Constraint"
                  onChange={(event) => setTimeConstraint(event.target.value)}
                >
                  {[...Array(60).keys()].map((value) => (
                    <MenuItem key={value} value={value + 1}>{value + 1} minute(s)</MenuItem>
                  ))}
                </Select>
              </FormControl> */}
              <FormControl>
                <MultiSelect
                  options={eventTypeOptions}
                  value={selectedEventTypes}
                  onChange={setSelectedEventTypes}
                  labelledBy="Select Event Types"
                />
              </FormControl>
              <Box sx={{ width: "100%", marginBottom: "15px" }}>
                <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
                  <Tabs value={tab} onChange={(_, value) => setTab(value)} aria-label="Tabs">
                    <Tab label="Table View" />
                    <Tab label="Timeline View" />
                    <Tab label="System Time" />
                  </Tabs>
                </Box>
              </Box>
              <Box sx={{ width: "100%", marginBottom: "15px" }}>
                {tab === 0 && <EventsView scheduleId={scheduleId} eventTypes={selectedEventTypes.map((type) => type.value)} />} 
                {tab === 1 && <ScheduleTimeline scheduleId={scheduleId} eventTypes={selectedEventTypes.map((type) => type.value)}/>}
                {tab == 2 && <SystemTime />} 
              </Box>
            </Container>
          </div>
        </div>
      </main>
    </>
  );
}